workflows:  
  ios-project-debug: # Workflow ID
    name: iOS Debug # Workflow name
    environment:
      xcode: latest
      cocoapods: default
      vars:
          BUNDLE_ID: "com.quannq.cicd" # replace with your app bundle
          XCODE_PROJECT: "cicd.xcodeproj" #  
          XCODE_SCHEME: "cicd" # Replace with your project name
      
    scripts:
      - name: Runs
        script: echo "Running"
      
    publishing:
      email:
        recipients:
          - quannq@mail.com # Replace with your email